CREATE SEQUENCE TRAFFIC_SENSOR_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TRAFFIC_SENSOR (
    ID INTEGER DEFAULT TRAFFIC_SENSOR_SEQ.NEXTVAL NOT NULL,
    LAT FLOAT(53) NOT NULL,
    LNG FLOAT(53) NOT NULL,
    AMOUNT FLOAT(53) NOT NULL,
    CREATED_AT DATE NOT NULL,
    UPDATED_AT DATE
);

CREATE SEQUENCE TRAFFIC_LIGHT_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TRAFFIC_LIGHT (
    ID INTEGER DEFAULT TRAFFIC_LIGHT_SEQ.NEXTVAL NOT NULL,
    LAT FLOAT(53) NOT NULL,
    LNG FLOAT(53) NOT NULL,
    STATUS VARCHAR2(255 CHAR) NOT NULL,
    CREATED_AT DATE NOT NULL,
    UPDATED_AT DATE
);