CREATE SEQUENCE ACCOUNT_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE ACCOUNT (
    ID INTEGER DEFAULT ACCOUNT_SEQ.NEXTVAL NOT NULL,
    NAME VARCHAR2(100 CHAR) NOT NULL,
    EMAIL VARCHAR2(100 CHAR) NOT NULL,
    PASSWORD VARCHAR2(20 CHAR) NOT NULL,
    ROLE VARCHAR2(10 CHAR) DEFAULT 'ACCOUNT',
    CREATED_AT DATE NOT NULL,
    UPDATED_AT DATE
);