name: CD
on:
  pull_request:
    branches:
      - main
jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build with Maven
        run: mvn -B package --file pom.xml

  docker:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Configurando o QEMU
        uses: docker/setup-qemu-action@v2

      - name: Configurando o Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Autenticando no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build e push das modificações
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          file: ./docker/Dockerfile.prod
          push: true
          tags: rm93287/traffic_management:${{ github.sha }}