name: CD
on:
  pull_request:
    branches:
      - main
jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

  docker:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Configurando o QEMU
        uses: docker/setup-qemu-action@v2

      - name: Configurando o Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Autenticando no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build e push das modificações
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          file: ./docker/Dockerfile.prod
          push: true
          tags: rm93287/traffic_management:${{ github.sha }}

  aws:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Set up kubectl
        run: |
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region sa-east-1


      - name: Atualizando a imagem no deployment
        run: kubectl set image deployment/btrace-rest-api-deployment btrace-rest-api-container=bwssoft/btrace-rest-api:prod-${{ github.sha }} -n btrace-rest-api

      - name: Verificando o deployment
        run: kubectl rollout status deployment/btrace-rest-api-deployment -n btrace-rest-api