name: CD
on:
  pull_request:
    branches:
      - main
jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build with Maven
        run: mvn clean package

      - name: Listar arquivos no diretório target
        run: ls -l target

      - name: Upload .jar file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: jar-file
          path: target/traffic_management_spring_boot-0.0.1-SNAPSHOT.jar

  docker:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - name: Baixar o artefato .jar
        uses: actions/download-artifact@v3
        with:
          name: jar-file
          path: ./target # Baixar o artefato para a pasta ./target

      - name: Listar arquivos no diretório target
        run: ls -l

      - name: Configurando o QEMU
        uses: docker/setup-qemu-action@v2

      - name: Configurando o Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Autenticando no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Listar arquivos no diretório target
        run: ls -l

      - name: Listar arquivos no diretório target
        run: ls -l target

      - name: Build e push das modificações
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          file: ./docker/Dockerfile.prod
          push: true
          tags: rm93287/traffic_management:${{ github.sha }}
          no-cache: true
